In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
#Import Streaming dataframe from CSV
parks_df = pd.read_csv('Data_Cleansing/parks.csv')
parks_df.head()

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETDIR,STREETNM,STREETTYPE,STREETSUFF,CITY,...,CITYCOUNCI,BOCC,PRKDATE,USERID,UPSIZE_TS,X,Y,LEASEDID,parklatitude,parklongitude
0,75,MACC,Matthews Community Center,100 E MCDOWELL ST,100,E,MCDOWELL,ST,NaN,MATTHEWS,...,NaN,District 6,NaN,NaN,NaN,1485035.915,500644.5184,Matthews,35.113161,-80.722521
1,66,HOBP,Holbrook Park,100 SHERWOOD DR,100,NaN,SHERWOOD,DR,NaN,HUNTERSVILLE,...,NaN,District 1,NaN,NaN,NaN,1450161.494,610322.0658,Huntersville,35.412999,-80.845105
2,266,BJCC,Belle Johnston Community Center,1000 JOHNSTON DR,1000,NaN,JOHNSTON,DR,NaN,PINEVILLE,...,NaN,District 6,NaN,NaN,NaN,1433803.316,488956.7933,Pineville,35.078633,-80.892896
3,40,HOWA,Howie Acres Park,1001 TREMBETH DR,1001,,TREMBETH,DR,,CHARLOTTE,...,District 1,District 3,1998/07/28 00:00:00+00,NaN,NaN,1467294.476,550544.5533,Mecklenburg,35.250215,-80.785024
4,181,THRD,James Dennis Rash Park,1001 W 4TH ST EXT,1001,W,4TH,ST,,CHARLOTTE,...,District 2,District 4,1998/07/28 00:00:00+00,NaN,NaN,1446096.741,544878.9741,Mecklenburg,35.232769,-80.855076

In [3]:
population_df = pd.read_csv('Data_Cleansing/Charlotte_Pop_and_Income.csv')
population_df.head()

,zipcode,lattitude,longitude,city,population,pplpersqmile,avgincomeperhshd
0,28223,35.301946,-80.734737,Charlotte,"3,265.00","7,150.18",-
1,28205,35.218791,-80.789601,Charlotte,"46,301.00","3,876.93","34,240.00"
2,28212,35.187703,-80.744556,Charlotte,"35,367.00","3,802.06","37,151.00"
3,28209,35.178714,-80.853985,Charlotte,"19,759.00","3,638.25","46,175.00"
4,28207,35.194148,-80.824585,Charlotte,"8,691.00","3,435.91","84,232.00"

In [4]:
parksandpop_df = pd.merge(parks_df, population_df, on="zipcode")
parksandpop_df

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETDIR,STREETNM,STREETTYPE,STREETSUFF,CITY,...,Y,LEASEDID,parklatitude,parklongitude,lattitude,longitude,city,population,pplpersqmile,avgincomeperhshd
0,40,HOWA,Howie Acres Park,1001 TREMBETH DR,1001,,TREMBETH,DR,,CHARLOTTE,...,550544.5533,Mecklenburg,35.250215,-80.785024,35.218791,-80.789601,Charlotte,"46,301.00","3,876.93","34,240.00"
1,154,LTLP,Little Peoples Park,1120 HARRILL ST,1200,,HARRILL,ST,,CHARLOTTE,...,543042.1736,Mecklenburg,35.228277,-80.820233,35.218791,-80.789601,Charlotte,"46,301.00","3,876.93","34,240.00"
2,293,PROG,Progress Park,1301 PARKWOOD AV,1301,,PARKWOOD,AV,,CHARLOTTE,...,544717.0293,Mecklenburg,35.233365,-80.812472,35.218791,-80.789601,Charlotte,"46,301.00","3,876.93","34,240.00"
3,283,SHLD,Sheffield Park,1311 TARRINGTON AV,1311,,TARRINGTON,AV,,CHARLOTTE,...,534645.3593,Mecklenburg,35.206368,-80.768059,35.218791,-80.789601,Charlotte,"46,301.00","3,876.93","34,240.00"
4,47,EVER,Evergreen Nature Preserve,1336 NORLAND RD,0,,NO ADDRESS,,,CHARLOTTE,...,535558.5032,Mecklenburg,35.208311,-80.777610,35.218791,-80.789601,Charlotte,"46,301.00","3,876.93","34,240.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,260,REDD,Reddman Road Park,6350 REDDMAN RD,6350,,REDDMAN,RD,,CHARLOTTE,...,530855.0224,Mecklenburg,35.196899,-80.752353,35.187703,-80.744556,Charlotte,"35,367.00","3,802.06","37,151.00"
225,71,CMCP,Campbell Creek Park,6601 BARCLIFF DR,6601,,BARCLIFFE,DR,,CHARLOTTE,...,537915.1491,Mecklenburg,35.215790,-80.735186,35.187703,-80.744556,Charlotte,"35,367.00","3,802.06","37,151.00"
226,76,CEDR,Cedarwood Park,6624 REDDMAN RD,6624,,REDDMAN,RD,,CHARLOTTE,...,529105.6791,Mecklenburg,35.191989,-80.751129,35.187703,-80.744556,Charlotte,"35,367.00","3,802.06","37,151.00"
227,67,MSNW,Mason Wallace Park,7301 MONROE RD,7301,,MONROE,RD,,CHARLOTTE,...,520579.8188,Mecklenburg,35.169199,-80.755893,35.187703,-80.744556,Charlotte,"35,367.00","3,802.06","37,151.00"
228,79,MCCP,McAlpine Creek Park,8711 MONROE RD,8711,,MONROE,RD,,CHARLOTTE,...,514435.2479,Mecklenburg,35.150876,-80.744933,35.187703,-80.744556,Charlotte,"35,367.00","3,802.06","37,151.00"

In [5]:
#Delete columns and confirm order of remaining columns
del parksandpop_df['STREETDIR']
del parksandpop_df['STREETSUFF']
del parksandpop_df['UPSIZE_TS']
del parksandpop_df['USERID']
del parksandpop_df['STREETTYPE']
del parksandpop_df['city']
parksandpop_df

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETNM,CITY,STATE,zipcode,PRKTYPE,...,X,Y,LEASEDID,parklatitude,parklongitude,lattitude,longitude,population,pplpersqmile,avgincomeperhshd
0,40,HOWA,Howie Acres Park,1001 TREMBETH DR,1001,TREMBETH,CHARLOTTE,NC,28205,Neighborhood,...,1467294.476,550544.5533,Mecklenburg,35.250215,-80.785024,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
1,154,LTLP,Little Peoples Park,1120 HARRILL ST,1200,HARRILL,CHARLOTTE,NC,28205,Neighborhood,...,1456404.896,543042.1736,Mecklenburg,35.228277,-80.820233,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
2,293,PROG,Progress Park,1301 PARKWOOD AV,1301,PARKWOOD,CHARLOTTE,NC,28205,Neighborhood,...,1458838.967,544717.0293,Mecklenburg,35.233365,-80.812472,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
3,283,SHLD,Sheffield Park,1311 TARRINGTON AV,1311,TARRINGTON,CHARLOTTE,NC,28205,Neighborhood,...,1472235.770,534645.3593,Mecklenburg,35.206368,-80.768059,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
4,47,EVER,Evergreen Nature Preserve,1336 NORLAND RD,0,NO ADDRESS,CHARLOTTE,NC,28205,Nature Preserve,...,1468972.751,535558.5032,Mecklenburg,35.208311,-80.777610,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,260,REDD,Reddman Road Park,6350 REDDMAN RD,6350,REDDMAN,CHARLOTTE,NC,28212,Community,...,1477267.252,530855.0224,Mecklenburg,35.196899,-80.752353,35.187703,-80.744556,"35,367.00","3,802.06","37,151.00"
225,71,CMCP,Campbell Creek Park,6601 BARCLIFF DR,6601,BARCLIFFE,CHARLOTTE,NC,28212,Community,...,1481781.309,537915.1491,Mecklenburg,35.215790,-80.735186,35.187703,-80.744556,"35,367.00","3,802.06","37,151.00"
226,76,CEDR,Cedarwood Park,6624 REDDMAN RD,6624,REDDMAN,CHARLOTTE,NC,28212,Neighborhood,...,1477174.592,529105.6791,Mecklenburg,35.191989,-80.751129,35.187703,-80.744556,"35,367.00","3,802.06","37,151.00"
227,67,MSNW,Mason Wallace Park,7301 MONROE RD,7301,MONROE,CHARLOTTE,NC,28212,Community,...,1475386.783,520579.8188,Mecklenburg,35.169199,-80.755893,35.187703,-80.744556,"35,367.00","3,802.06","37,151.00"
228,79,MCCP,McAlpine Creek Park,8711 MONROE RD,8711,MONROE,CHARLOTTE,NC,28212,Regional,...,1478221.489,514435.2479,Mecklenburg,35.150876,-80.744933,35.187703,-80.744556,"35,367.00","3,802.06","37,151.00"

In [6]:
#Delete columns and confirm order of remaining columns
del parksandpop_df['PRKSIZE']
del parksandpop_df['PRKXCOORD']
del parksandpop_df['PRKYCOORD']
del parksandpop_df['PRKAGE']
del parksandpop_df['PRKADAACC']
parksandpop_df.head()

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETNM,CITY,STATE,zipcode,PRKTYPE,...,X,Y,LEASEDID,parklatitude,parklongitude,lattitude,longitude,population,pplpersqmile,avgincomeperhshd
0,40,HOWA,Howie Acres Park,1001 TREMBETH DR,1001,TREMBETH,CHARLOTTE,NC,28205,Neighborhood,...,1467294.476,550544.5533,Mecklenburg,35.250215,-80.785024,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
1,154,LTLP,Little Peoples Park,1120 HARRILL ST,1200,HARRILL,CHARLOTTE,NC,28205,Neighborhood,...,1456404.896,543042.1736,Mecklenburg,35.228277,-80.820233,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
2,293,PROG,Progress Park,1301 PARKWOOD AV,1301,PARKWOOD,CHARLOTTE,NC,28205,Neighborhood,...,1458838.967,544717.0293,Mecklenburg,35.233365,-80.812472,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
3,283,SHLD,Sheffield Park,1311 TARRINGTON AV,1311,TARRINGTON,CHARLOTTE,NC,28205,Neighborhood,...,1472235.770,534645.3593,Mecklenburg,35.206368,-80.768059,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
4,47,EVER,Evergreen Nature Preserve,1336 NORLAND RD,0,NO ADDRESS,CHARLOTTE,NC,28205,Nature Preserve,...,1468972.751,535558.5032,Mecklenburg,35.208311,-80.777610,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"

In [7]:
#output to CSV
parksandpop_df.to_csv("parksandpop.csv", index=False, header=True)

In [8]:
parksandpop_df.head()

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETNM,CITY,STATE,zipcode,PRKTYPE,...,X,Y,LEASEDID,parklatitude,parklongitude,lattitude,longitude,population,pplpersqmile,avgincomeperhshd
0,40,HOWA,Howie Acres Park,1001 TREMBETH DR,1001,TREMBETH,CHARLOTTE,NC,28205,Neighborhood,...,1467294.476,550544.5533,Mecklenburg,35.250215,-80.785024,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
1,154,LTLP,Little Peoples Park,1120 HARRILL ST,1200,HARRILL,CHARLOTTE,NC,28205,Neighborhood,...,1456404.896,543042.1736,Mecklenburg,35.228277,-80.820233,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
2,293,PROG,Progress Park,1301 PARKWOOD AV,1301,PARKWOOD,CHARLOTTE,NC,28205,Neighborhood,...,1458838.967,544717.0293,Mecklenburg,35.233365,-80.812472,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
3,283,SHLD,Sheffield Park,1311 TARRINGTON AV,1311,TARRINGTON,CHARLOTTE,NC,28205,Neighborhood,...,1472235.770,534645.3593,Mecklenburg,35.206368,-80.768059,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
4,47,EVER,Evergreen Nature Preserve,1336 NORLAND RD,0,NO ADDRESS,CHARLOTTE,NC,28205,Nature Preserve,...,1468972.751,535558.5032,Mecklenburg,35.208311,-80.777610,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"

In [9]:
parksformat_df = parksandpop_df.rename(columns={'OBJECTID': 'objectid', 'PRKID': 'parkid', 'PRKNAME': 'parkname',
                                                'PRKADDR': 'parkaddress', 'STREETNO': 'streetno','STREETNM': 'streetname',
                                                'CITY': 'city', 'STATE': 'state', 'zipcode':'zipcode','PRKTYPE': 'parktype',
                                                'PRKCAT': 'parkcatagory', 'PRKSTATUS': 'parkstatus', 'PRKDIST': 'parkdist',
                                                'PRKPHONE': 'parkphone','CITYCOUNCI': 'councildistrict', 'BOCC': 'bocc',
                                                'PRKDATE': 'parkdate', 'X': 'x', 'Y': 'y', 'parklatitude': 'parklatitude', 
                                                'parklongitude': 'parklongitude', 'LEASEDID': 'leasedid',
                                                'Lattitude': 'lattitude', 'longitude': 'longitude', 'population': 'population',
                                                'pplpersqmile': 'pplpersqmile', 'avgincomeperhshd': 'avgincomeperhshd'})
parksformat_df.head()

,objectid,parkid,parkname,parkaddress,streetno,streetname,city,state,zipcode,parktype,...,x,y,leasedid,parklatitude,parklongitude,lattitude,longitude,population,pplpersqmile,avgincomeperhshd
0,40,HOWA,Howie Acres Park,1001 TREMBETH DR,1001,TREMBETH,CHARLOTTE,NC,28205,Neighborhood,...,1467294.476,550544.5533,Mecklenburg,35.250215,-80.785024,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
1,154,LTLP,Little Peoples Park,1120 HARRILL ST,1200,HARRILL,CHARLOTTE,NC,28205,Neighborhood,...,1456404.896,543042.1736,Mecklenburg,35.228277,-80.820233,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
2,293,PROG,Progress Park,1301 PARKWOOD AV,1301,PARKWOOD,CHARLOTTE,NC,28205,Neighborhood,...,1458838.967,544717.0293,Mecklenburg,35.233365,-80.812472,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
3,283,SHLD,Sheffield Park,1311 TARRINGTON AV,1311,TARRINGTON,CHARLOTTE,NC,28205,Neighborhood,...,1472235.770,534645.3593,Mecklenburg,35.206368,-80.768059,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"
4,47,EVER,Evergreen Nature Preserve,1336 NORLAND RD,0,NO ADDRESS,CHARLOTTE,NC,28205,Nature Preserve,...,1468972.751,535558.5032,Mecklenburg,35.208311,-80.777610,35.218791,-80.789601,"46,301.00","3,876.93","34,240.00"

In [10]:
#output to CSV
parksformat_df.to_csv("parksdataframe.csv", index=False, header=True)

In [11]:
rds_connection_string = "postgres:Armadi!!0405@localhost:5432/parks_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [12]:
engine.table_names()

['parks_ev', 'parks', 'zipcode_coord']

In [13]:
parksformat_df.to_sql(name='parks', con=engine, if_exists='append', index=False)

In [14]:
#Import events
parks_ev_df = pd.read_csv('static/parkevents_df.csv')
parks_ev_df.head()

                                         Park_Events
0                                  BWRC: Afterschool
1                 BWRC: Remote (WEDNESDAYS) Full Day
2  County Employee Fitness Classes (Virtual) Mar ...
3                           ERRC: Intro to Disc Golf
4                       ERRC: Parking Lot Pickleball

In [15]:
parks_ev = parks_ev_df.rename(columns={'Park_Events': 'park_events', 'date': 'date'})
parks_ev

                                          park_events
0                                   BWRC: Afterschool
1                  BWRC: Remote (WEDNESDAYS) Full Day
2   County Employee Fitness Classes (Virtual) Mar ...
3                            ERRC: Intro to Disc Golf
4                        ERRC: Parking Lot Pickleball
5            ERRC: Specialty Summer Camp Program 2021
6                             SVRC: Flip That Workout
7                       SVRC: Senior Trivia and Games
8             SVRC: Southview Senior Outdoor Programs
9          SVRC: Southview Virtual Preschool Programs
10                              SVRC: Spring Egg Hunt
11                    SVRC: Virtual Family Game Night
12                              SVRC: Virtual Zumbini
13                   SVRC: What's the Word Wednesdays
14                                 TYSC: Table Tennis
15                            RCNP: Walk for Wellness
16                            RCNP: Walk for Wellness
17                            RCNP: Walk for Wellness
18                            RCNP: Walk for Wellness
19                            RCNP: Walk for Wellness
20                            Starts from Mon, Apr 12
21                            Starts from Wed, Apr 14
22                            Starts from Mon, Mar 22
23                             Starts from Mon, Jun 7
24                            Starts from Tue, Mar 16
25                            Starts from Mon, Jun 14
26                            Starts from Mon, Apr 12
27                             Starts from Mon, Apr 5
28                             Starts from Thu, Apr 1
29                             Starts from Thu, Apr 1
30                             Starts from Thu, Apr 8
31                             Starts from Thu, Apr 1
32                             Starts from Thu, Apr 1
33                             Starts from Thu, Apr 1
34                             Starts from Wed, Jun 2
35                                       June 4, 2021
36                                      June 11, 2021
37                                      June 18, 2021
38                                      June 25, 2021
39                                        May 7, 2021

In [16]:
rds_connection_string = "postgres:Armadi!!0405@localhost:5432/parks_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [17]:
engine.table_names()

['parks_ev', 'parks', 'zipcode_coord']

In [18]:
parks_ev.to_sql(name='parks_ev', con=engine, if_exists='append', index=False)

In [19]:
#Import zipcode cooridinates
zipcord_df = pd.read_csv('Census_Household_Income_Block_Groups.csv')
zipcord_df.head()

,zipcode,geometry,coordinates,objectid,statefp10,countyfp10,tractce10,blkgrpce10,geoid10,namelsad10,...,i100000_to_124999,i125000_to_149999,i150000_to_199999,i200000_or_more,median_household_income,totalfamilies,familiesinpoverty,familypovertyrate,shapestarea,shapestlength
0,28212,Polygon,"-80.73717220926873,35.21724688361553,-80.73723...",2776,37,119,1609,2,3.711900e+11,Block Group 2,...,68,32,10,0,45963,558,14,0.208577,5.838492e+06,11934.20645
1,28273,Polygon,"-80.87993624647164,35.12189185809053,-80.88020...",2777,37,119,3109,1,3.711900e+11,Block Group 1,...,49,0,37,0,43609,513,107,0.208577,5.838492e+06,11934.20645
2,28031,Polygon,"-80.8586082616796,35.483604934149675,-80.85832...",2778,37,119,6405,2,3.711900e+11,Block Group 2,...,141,30,147,147,85258,622,14,0.022508,9.416605e+07,46805.88409
3,28207,Polygon,"-80.84028523784471,35.18626287248248,-80.84031...",2779,37,119,2702,1,3.711900e+11,Block Group 1,...,30,103,70,368,180175,550,14,0.025455,1.737750e+07,18116.21139
4,28226,Polygon,"-80.8247702292179,35.09214185281286,-80.825076...",2780,37,119,3013,1,3.711900e+11,Block Group 1,...,62,81,152,522,194514,849,14,0.016490,3.709292e+07,36604.35413

In [20]:
rds_connection_string = "postgres:Armadi!!0405@localhost:5432/parks_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [21]:
engine.table_names()

['parks_ev', 'parks', 'zipcode_coord']

In [22]:
zipcord_df.to_sql(name='zipcode_coord', con=engine, if_exists='append', index=False)