In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
#Import Streaming dataframe from CSV
parks_df = pd.read_csv('parks.csv')
parks_df.head()

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETDIR,STREETNM,STREETTYPE,STREETSUFF,CITY,...,PRKAGE,PRKADAACC,CITYCOUNCI,BOCC,PRKDATE,USERID,UPSIZE_TS,X,Y,LEASEDID
0,1,CLAG,Clanton Park Community Garden,3010 BARRINGER DR,3010,NaN,BARRINGER,DR,NaN,CHARLOTTE,...,NaN,NaN,District 3,District 2,2019/03/25 16:29:41+00,NaN,NaN,1437598.029,535681.4151,Mecklenburg
1,2,COLL,Collins Park,4525 COLLINGWOOD DR,4525,,COLLINGWOOD,DR,,CHARLOTTE,...,NaN,NaN,District 1,District 5,1998/07/28 00:00:00+00,NaN,NaN,1440896.750,526061.0002,Mecklenburg
2,3,CTMY,C.T. Myers Golf Course,7817 HARRISBURG RD,7817,,HARRISBURG,RD,,CHARLOTTE,...,NaN,NaN,District 5,District 4,2002/03/18 00:00:00+00,NaN,NaN,1496508.108,539832.7766,Mecklenburg
3,4,THMP,Thompson Park,1125 E 3RD ST,1125,E,3RD,ST,NO,CHARLOTTE,...,NaN,NaN,District 1,District 4,1998/09/02 00:00:00+00,NaN,NaN,1452180.288,538692.2129,Mecklenburg
4,5,AMSG,Alexander Middle School Gymnasium,12010 HAMBRIGHT RD,12010,NaN,HAMBRIGHT,RD,NaN,HUNTERSVILLE,...,NaN,NaN,NaN,District 1,NaN,NaN,NaN,1452055.592,596972.0006,Huntersville

In [3]:
population_df = pd.read_csv('Charlotte_Pop_and_Income.csv')
population_df.head()

,zipcode,lattitude,longitude,city,population,pplpersqmile,avgincomeperhshd
0,28223,35.301946,-80.734737,Charlotte,"3,265.00","7,150.18",-
1,28205,35.218791,-80.789601,Charlotte,"46,301.00","3,876.93","34,240.00"
2,28212,35.187703,-80.744556,Charlotte,"35,367.00","3,802.06","37,151.00"
3,28209,35.178714,-80.853985,Charlotte,"19,759.00","3,638.25","46,175.00"
4,28207,35.194148,-80.824585,Charlotte,"8,691.00","3,435.91","84,232.00"

In [4]:
parksandpop_df = pd.merge(parks_df, population_df, on="zipcode")
parksandpop_df

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETDIR,STREETNM,STREETTYPE,STREETSUFF,CITY,...,UPSIZE_TS,X,Y,LEASEDID,lattitude,longitude,city,population,pplpersqmile,avgincomeperhshd
0,1,CLAG,Clanton Park Community Garden,3010 BARRINGER DR,3010,NaN,BARRINGER,DR,NaN,CHARLOTTE,...,NaN,1437598.029,535681.4151,Mecklenburg,35.168896,-80.908285,Charlotte,"19,388.00","1,301.44","38,757.00"
1,32,CLAN,Clanton Park,1520 CLANTON RD,1520,,CLANTON,AV,,CHARLOTTE,...,NaN,1434491.148,536050.4650,Mecklenburg,35.168896,-80.908285,Charlotte,"19,388.00","1,301.44","38,757.00"
2,44,SPRG,Springfield Park,6700 DEANWOOD PL,6700,,DEANWOOD,PL,,CHARLOTTE,...,NaN,1431135.076,518528.0594,Mecklenburg,35.168896,-80.908285,Charlotte,"19,388.00","1,301.44","38,757.00"
3,70,RSPK,Renaissance Park,1536 W TYVOLA RD,1536,W,TYVOLA,RD,,CHARLOTTE,...,NaN,1429340.235,524412.7907,Mecklenburg,35.168896,-80.908285,Charlotte,"19,388.00","1,301.44","38,757.00"
4,150,CLAP,Dorothy D. Waddy Pavilion,3132 MANCHESTER DR,3132,NaN,MANCHESTER,DR,NaN,CHARLOTTE,...,NaN,1437385.001,535127.0001,Mecklenburg,35.168896,-80.908285,Charlotte,"19,388.00","1,301.44","38,757.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,116,BCKP,Back Creek Park,3343 BACK CREEK CHURCH RD,0,,NO ADDRESS,,,CHARLOTTE,...,NaN,1492047.596,564895.0866,Mecklenburg,35.286034,-80.734355,Charlotte,"25,882.00","1,907.01","41,340.00"
225,197,MLKR,Martin Luther King Jr. Middle School Site,500 BILMARK AV,0,,,,,CHARLOTTE,...,NaN,1468942.507,555464.0724,Mecklenburg,35.286034,-80.734355,Charlotte,"25,882.00","1,907.01","41,340.00"
226,215,NEWP,Newell Park,9130 NEWELL BAPTIST CHURCH RD,9130,,NEWELL BAPTIST CHURCH,RD,,CHARLOTTE,...,NaN,1482307.750,563623.7502,Mecklenburg,35.286034,-80.734355,Charlotte,"25,882.00","1,907.01","41,340.00"
227,274,SUGC,Sugaw Creek Recreation Center,943 W SUGAR CREEK RD,943,W,SUGAR CREEK,RD,,CHARLOTTE,...,NaN,1463875.508,558915.3095,Mecklenburg,35.286034,-80.734355,Charlotte,"25,882.00","1,907.01","41,340.00"
228,281,HIDD,Hidden Valley Park,260 NORTHCHASE DR,0,,,,NO,CHARLOTTE,...,NaN,1469748.130,555552.3194,Mecklenburg,35.286034,-80.734355,Charlotte,"25,882.00","1,907.01","41,340.00"

In [5]:
#Delete columns and confirm order of remaining columns
del parksandpop_df['STREETDIR']
del parksandpop_df['STREETSUFF']
del parksandpop_df['UPSIZE_TS']
del parksandpop_df['USERID']
del parksandpop_df['STREETTYPE']
del parksandpop_df['city']
parksandpop_df

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETNM,CITY,STATE,zipcode,PRKTYPE,...,BOCC,PRKDATE,X,Y,LEASEDID,lattitude,longitude,population,pplpersqmile,avgincomeperhshd
0,1,CLAG,Clanton Park Community Garden,3010 BARRINGER DR,3010,BARRINGER,CHARLOTTE,NC,28217,Community Garden,...,District 2,2019/03/25 16:29:41+00,1437598.029,535681.4151,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
1,32,CLAN,Clanton Park,1520 CLANTON RD,1520,CLANTON,CHARLOTTE,NC,28217,Community,...,District 2,1998/07/28 00:00:00+00,1434491.148,536050.4650,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
2,44,SPRG,Springfield Park,6700 DEANWOOD PL,6700,DEANWOOD,CHARLOTTE,NC,28217,Neighborhood,...,District 2,1998/07/28 00:00:00+00,1431135.076,518528.0594,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
3,70,RSPK,Renaissance Park,1536 W TYVOLA RD,1536,TYVOLA,CHARLOTTE,NC,28217,Regional,...,District 2,2002/02/01 00:00:00+00,1429340.235,524412.7907,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
4,150,CLAP,Dorothy D. Waddy Pavilion,3132 MANCHESTER DR,3132,MANCHESTER,CHARLOTTE,NC,28217,Pavilion,...,District 2,2019/02/25 16:36:18+00,1437385.001,535127.0001,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,116,BCKP,Back Creek Park,3343 BACK CREEK CHURCH RD,0,NO ADDRESS,CHARLOTTE,NC,28213,Regional,...,District 3,2002/03/18 00:00:00+00,1492047.596,564895.0866,Mecklenburg,35.286034,-80.734355,"25,882.00","1,907.01","41,340.00"
225,197,MLKR,Martin Luther King Jr. Middle School Site,500 BILMARK AV,0,,CHARLOTTE,NC,28213,Recreation Center,...,District 3,NaN,1468942.507,555464.0724,Mecklenburg,35.286034,-80.734355,"25,882.00","1,907.01","41,340.00"
226,215,NEWP,Newell Park,9130 NEWELL BAPTIST CHURCH RD,9130,NEWELL BAPTIST CHURCH,CHARLOTTE,NC,28213,Community,...,District 3,1998/08/12 00:00:00+00,1482307.750,563623.7502,Mecklenburg,35.286034,-80.734355,"25,882.00","1,907.01","41,340.00"
227,274,SUGC,Sugaw Creek Recreation Center,943 W SUGAR CREEK RD,943,SUGAR CREEK,CHARLOTTE,NC,28213,Recreation Center,...,District 3,1998/07/28 00:00:00+00,1463875.508,558915.3095,Mecklenburg,35.286034,-80.734355,"25,882.00","1,907.01","41,340.00"
228,281,HIDD,Hidden Valley Park,260 NORTHCHASE DR,0,,CHARLOTTE,NC,28213,Neighborhood,...,District 3,2000/05/23 00:00:00+00,1469748.130,555552.3194,Mecklenburg,35.286034,-80.734355,"25,882.00","1,907.01","41,340.00"

In [6]:
#Delete columns and confirm order of remaining columns
del parksandpop_df['PRKSIZE']
del parksandpop_df['PRKXCOORD']
del parksandpop_df['PRKYCOORD']
del parksandpop_df['PRKAGE']
del parksandpop_df['PRKADAACC']
parksandpop_df.head()

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETNM,CITY,STATE,zipcode,PRKTYPE,...,BOCC,PRKDATE,X,Y,LEASEDID,lattitude,longitude,population,pplpersqmile,avgincomeperhshd
0,1,CLAG,Clanton Park Community Garden,3010 BARRINGER DR,3010,BARRINGER,CHARLOTTE,NC,28217,Community Garden,...,District 2,2019/03/25 16:29:41+00,1437598.029,535681.4151,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
1,32,CLAN,Clanton Park,1520 CLANTON RD,1520,CLANTON,CHARLOTTE,NC,28217,Community,...,District 2,1998/07/28 00:00:00+00,1434491.148,536050.4650,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
2,44,SPRG,Springfield Park,6700 DEANWOOD PL,6700,DEANWOOD,CHARLOTTE,NC,28217,Neighborhood,...,District 2,1998/07/28 00:00:00+00,1431135.076,518528.0594,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
3,70,RSPK,Renaissance Park,1536 W TYVOLA RD,1536,TYVOLA,CHARLOTTE,NC,28217,Regional,...,District 2,2002/02/01 00:00:00+00,1429340.235,524412.7907,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
4,150,CLAP,Dorothy D. Waddy Pavilion,3132 MANCHESTER DR,3132,MANCHESTER,CHARLOTTE,NC,28217,Pavilion,...,District 2,2019/02/25 16:36:18+00,1437385.001,535127.0001,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"

In [9]:
#output to CSV
parksandpop_df.to_csv("parksandpop.csv", index=False, header=True)

In [10]:
parksandpop_df.head()

,OBJECTID,PRKID,PRKNAME,PRKADDR,STREETNO,STREETNM,CITY,STATE,zipcode,PRKTYPE,...,BOCC,PRKDATE,X,Y,LEASEDID,lattitude,longitude,population,pplpersqmile,avgincomeperhshd
0,1,CLAG,Clanton Park Community Garden,3010 BARRINGER DR,3010,BARRINGER,CHARLOTTE,NC,28217,Community Garden,...,District 2,2019/03/25 16:29:41+00,1437598.029,535681.4151,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
1,32,CLAN,Clanton Park,1520 CLANTON RD,1520,CLANTON,CHARLOTTE,NC,28217,Community,...,District 2,1998/07/28 00:00:00+00,1434491.148,536050.4650,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
2,44,SPRG,Springfield Park,6700 DEANWOOD PL,6700,DEANWOOD,CHARLOTTE,NC,28217,Neighborhood,...,District 2,1998/07/28 00:00:00+00,1431135.076,518528.0594,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
3,70,RSPK,Renaissance Park,1536 W TYVOLA RD,1536,TYVOLA,CHARLOTTE,NC,28217,Regional,...,District 2,2002/02/01 00:00:00+00,1429340.235,524412.7907,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
4,150,CLAP,Dorothy D. Waddy Pavilion,3132 MANCHESTER DR,3132,MANCHESTER,CHARLOTTE,NC,28217,Pavilion,...,District 2,2019/02/25 16:36:18+00,1437385.001,535127.0001,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"

In [11]:
parksformat_df = parksandpop_df.rename(columns={'OBJECTID': 'objectid', 'PRKID': 'parkid', 'PRKNAME': 'parkname',
                                                'PRKADDR': 'parkaddress', 'STREETNO': 'streetno','STREETNM': 'streetname',
                                                'CITY': 'city', 'STATE': 'state', 'zipcode':'zipcode','PRKTYPE': 'parktype',
                                                'PRKCAT': 'parkcatagory', 'PRKSTATUS': 'parkstatus', 'PRKDIST': 'parkdist',
                                                'PRKPHONE': 'parkphone','CITYCOUNCI': 'councildistrict', 'BOCC': 'bocc',
                                                'PRKDATE': 'parkdate', 'X': 'x', 'Y': 'y', 'LEASEDID': 'leasedid',
                                                'Lattitude': 'lattitude', 'longitude': 'longitude', 'population': 'population',
                                                'pplpersqmile': 'pplpersqmile', 'avgincomeperhshd': 'avgincomeperhshd'})
parksformat_df.head()

,objectid,parkid,parkname,parkaddress,streetno,streetname,city,state,zipcode,parktype,...,bocc,parkdate,x,y,leasedid,lattitude,longitude,population,pplpersqmile,avgincomeperhshd
0,1,CLAG,Clanton Park Community Garden,3010 BARRINGER DR,3010,BARRINGER,CHARLOTTE,NC,28217,Community Garden,...,District 2,2019/03/25 16:29:41+00,1437598.029,535681.4151,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
1,32,CLAN,Clanton Park,1520 CLANTON RD,1520,CLANTON,CHARLOTTE,NC,28217,Community,...,District 2,1998/07/28 00:00:00+00,1434491.148,536050.4650,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
2,44,SPRG,Springfield Park,6700 DEANWOOD PL,6700,DEANWOOD,CHARLOTTE,NC,28217,Neighborhood,...,District 2,1998/07/28 00:00:00+00,1431135.076,518528.0594,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
3,70,RSPK,Renaissance Park,1536 W TYVOLA RD,1536,TYVOLA,CHARLOTTE,NC,28217,Regional,...,District 2,2002/02/01 00:00:00+00,1429340.235,524412.7907,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"
4,150,CLAP,Dorothy D. Waddy Pavilion,3132 MANCHESTER DR,3132,MANCHESTER,CHARLOTTE,NC,28217,Pavilion,...,District 2,2019/02/25 16:36:18+00,1437385.001,535127.0001,Mecklenburg,35.168896,-80.908285,"19,388.00","1,301.44","38,757.00"

In [12]:
#output to CSV
parksformat_df.to_csv("parksdataframe.csv", index=False, header=True)

In [13]:
rds_connection_string = "postgres:Jacky0509@localhost:5432/parks_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [14]:
engine.table_names()

['parks']

In [15]:
parksformat_df.to_sql(name='parks', con=engine, if_exists='append', index=False)